### ISSUE TITLE
Option selected

### ISSUE THREAD

**Issue by DIYLAB-DE** [regnaDkciN/WiFiTimeManager#1]
Many thanks for the WiFiTimemanager!
Unfortunately, I can't get any further at one point.
In the WebPages.h file, I would like to mark some entries as "selected" so that they are displayed as standard in the web interface.

For example, in this line here: 

`<option value="60">(GMT +1:00) Brussels, Copenhagen, Madrid, Paris</option>`

There causes a:

`<option value="60" selected>(GMT +1:00) Brussels, Copenhagen, Madrid, Paris</option>`

...unfortunately does nothing.

What do I have to do to make this time zone the default?

**Comment by DIYLAB-DE** [comment]
Ahhh - I've found it :)
Either there's nothing about it in the documentation, or I didn't read it.

Problem solved, thanks.

```
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Default timezone and DST values.  CHANGE THESE AS DESIRED.
// These are used only on the first startup of the program.  After that,
// (possibly) updated values are stored in and recovered from NVS on each
// startup.  The TP_VERSION value should be bumped any time a change is made
// to the structure.
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
static const uint32_t TP_VERSION           = 7;       // Struct version.  Bump on changes.
static const int32_t  DFLT_TZ_OFST         = -300;    // Eastern time (5 hrs behind).
static const char    *DFLT_TZ_ABBREV       = "EST";   // DST end rule abbreviation.
static const bool     DFLT_USE_DST         = true;    // true to use DST.
static const int32_t  DFLT_DST_OFST        = 60;      // 30 or 60 minute DST offset.
static const char    *DFLT_DST_START_ABBREV= "EDT";   // DST start rule abbreviation.
static const uint32_t DFLT_DST_START_WK    = wkSecond;// DST starts 2nd
static const uint32_t DFLT_DST_START_DOW   = dowSun;  //    Sunday
static const uint32_t DFLT_DST_START_MONTH = mMar;    //    of March
static const uint32_t DFLT_DST_START_HOUR  = 2;       //    at 2 AM.
static const uint32_t DFLT_DST_END_WK      = wkFirst; // DST ends 1st
static const uint32_t DFLT_DST_END_DOW     = dowSun;  //    Sunday
static const uint32_t DFLT_DST_END_MONTH   = mNov;    //    of November
static const uint32_t DFLT_DST_END_HOUR    = 2;       //    at 2 AM.
static const char    *DFLT_NTP_ADDR        = "time.nist.gov";   // NTP server
```

**Comment by regnaDkciN** [comment]
Glad you figured it out.
    On Saturday, April 13, 2024 at 03:23:32 AM EDT, Bruno ***@***.***> wrote:  
 
 


Ahhh - I've found it :)
Either there's nothing about it in the documentation, or I didn't read it.

Problem solved, thanks.
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Default timezone and DST values.  CHANGE THESE AS DESIRED.
// These are used only on the first startup of the program.  After that,
// (possibly) updated values are stored in and recovered from NVS on each
// startup.  The TP_VERSION value should be bumped any time a change is made
// to the structure.
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
static const uint32_t TP_VERSION           = 7;       // Struct version.  Bump on changes.
static const int32_t  DFLT_TZ_OFST         = -300;    // Eastern time (5 hrs behind).
static const char    *DFLT_TZ_ABBREV       = "EST";   // DST end rule abbreviation.
static const bool     DFLT_USE_DST         = true;    // true to use DST.
static const int32_t  DFLT_DST_OFST        = 60;      // 30 or 60 minute DST offset.
static const char    *DFLT_DST_START_ABBREV= "EDT";   // DST start rule abbreviation.
static const uint32_t DFLT_DST_START_WK    = wkSecond;// DST starts 2nd
static const uint32_t DFLT_DST_START_DOW   = dowSun;  //    Sunday
static const uint32_t DFLT_DST_START_MONTH = mMar;    //    of March
static const uint32_t DFLT_DST_START_HOUR  = 2;       //    at 2 AM.
static const uint32_t DFLT_DST_END_WK      = wkFirst; // DST ends 1st
static const uint32_t DFLT_DST_END_DOW     = dowSun;  //    Sunday
static const uint32_t DFLT_DST_END_MONTH   = mNov;    //    of November
static const uint32_t DFLT_DST_END_HOUR    = 2;       //    at 2 AM.
static const char    *DFLT_NTP_ADDR        = "time.nist.gov";   // NTP server
